### ISSUE TITLE
PsiStore Importer Missing Data Edgecase

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/psi#104]
I found an edge case where data from a PsiStore won't be imported under certain specific scenarios. I think it might have to do with streams with only a single message (e.g. DepthCalibration Information) among multiple streams.

Here's an example PsiStore: [example PsiStore](https://www.dropbox.com/sh/6gjph34sj59hkl1/AABnpustXhNO_LH4tfdzOfada?dl=0)

In the PsiStore, there is a stream `k2d1.depth-calibration` that has a single message. However, if you run the following code:
```
            using (var p = Pipeline.Create(enableDiagnostics: true))
            {
                var input = PsiStore.Open(p, "calibration-recording", @"C:\Data\Broken\broken-recording");
                var calibration = input.OpenStream<IDepthDeviceCalibrationInfo>("k2d1.depth-calibration");
                //var calibration2 = input.OpenStream<IDepthDeviceCalibrationInfo>("azure1.depth-calibration");
                calibration.Do((m,e) => Console.WriteLine("Hello"));
                p.Run();
            }
```
The console never prints `Hello`. However, when I uncomment `var calibration2`, it will work. I sort of trace it back to the way indexing of PsiStores are done and it picking the wrong starting position, but I lack the knowledge on the inner working to know exactly what happened. Please let me know if this just a quirk on my computer or it's reproducible.

**Comment by chitsaw** [comment]
It's reproducible. Investigating...

**Comment by chitsaw** [comment]
Yep, it's a bug. Thanks for reporting this.

**Comment by xiangzhi** [comment]
Awesome, thanks for the speedy fix!
