### ISSUE TITLE
Kinect sample crashes due to empty Face list

### ISSUE THREAD

**Issue by admayber** [Microsoft/psi#16]
The Kinect face tracking + speech-to-text sample throws an uncaught exception on the first frame when running. I determined that the error is due to KinectFaceDetector.Faces emitting a list with zero items under a Select operation, in these two lines:

`var mouthOpenAsFloat = kinectFaceDetector.Faces.Select((List<Microsoft.Psi.Kinect.Face.KinectFace> list) =>` (line 85)
`var landmarks = kinectFaceDetector.Faces.Select((List<Microsoft.Psi.Kinect.Face.KinectFace> list) =>` (line 116)

In both cases, the code block inside the Select crashes due to an empty list. I correct it by adding list.Count > 0 tests in both blocks; however, I'm not sure if this is the intended operation of the Select operator or if it should not have fired at all.

**Comment by chitsaw** [comment]
Thanks for reporting this issue. We'll investigate.
