### ISSUE TITLE
JsonFormat doesn't deserialize json nested in array

### ISSUE THREAD

**Issue by profwillie** [microsoft/psi#177]
The following message being sent over ZeroMQ does not deserialize properly:

`{"intent":"vanilla","description":"","actionList":[{"name":"SayText","args":["Keep up the great work!"]},{"name":"SetEyes","args":["default"]},{"name":"Pause","args":["200"]},{"name":"PointAt","args":["default","both"]},{"name":"LookInDirection","args":["center"]}]}
`

The problem is on line 99 of JsonFormat.cs.  The line:

`return tok.Children<JValue>().Select(this.JObjectToDynamic).ToArray();`

should be:

`return tok.Children().Select(this.JObjectToDynamic).ToArray();`

**Comment by AshleyF** [comment]
Thanks for pointing this out! This [fix has been made](https://github.com/microsoft/psi/pull/179).
