### ISSUE TITLE
Connecting Emitter Stream to Multiple Receiver Streams

### ISSUE THREAD

**Issue by amussell** [Microsoft/psi#19]
It seems that it is not possible to connect a single ConsumerProducer component to multiple Consumer components. I cannot find anything about doing this in the docs. Is there any reason why this should not be possible? Are there plans to make this possible?

**Comment by chitsaw** [comment]
If you mean connecting the output of a component (in Psi, component outputs are also referred to as **Emitters**) to multiple **Receivers**, then this is currently possible:
```csharp
using (var p = Pipeline.Create())
{
    // Create a WAV file audio source component
    var audioSource = new WaveFileAudioSource(p, "sample.wav");

    // Create an audio resampler component (a ConsumerProducer)
    var audioResampler = new AudioResampler(p, new AudioResamplerConfiguration() { OutputFormat = WaveFormat.Create16kHz1Channel16BitPcm() });

    // Pipe the output of the audio source to the resampler
    audioSource.PipeTo(audioResampler);

    // Pipe the output of the resampler to multiple consumer components
    var audioPlayer = new AudioPlayer(p, new AudioPlayerConfiguration());
    var audioFileWriter = new WaveFileWriter(p, "output.wav");
    audioResampler.PipeTo(audioPlayer);
    audioResampler.PipeTo(audioFileWriter);

    // Run the pipeline
    p.Run();
}
```

**Comment by amussell** [comment]
Oops it seems I was confused. I was actually trying to connect a receiver to multiple emitters. I would still like to be able to do this... I think. 

When I try I get the following error: System.InvalidOperationException: 'This receiver is already connected to a source emitter.'

Whats the reasoning behind not allowing this?

It looks like I just need to create two copies of a component to accomplish the same thing. But in my case I really don't need to distinguish between the sources. I can think of other cases where this might also be true.

I am just printing the output of different components to the console. I really only want one console component.

-To accomplish parallelism (Copy a component to to split the work of one stream to multiple copies of the component)
-If multiple sensors can detect the same event. I might not care where the event came from just that it occurred. I could connect each sensor to the event handling component given that each sensor is outputting the same type of event. (I.E. ringing a bell when detecting if someone has entered a room with multiple doors. Each door has a sensor on it).

Here is the code sample I am working with.
`
namespace Microsoft.Psi.Samples.GoogleSpeech
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using global::GoogleAudioTranslate;
    using Microsoft.Psi.Audio;

    namespace GoogleAudioTranslate
    {
        class Program
        {
            static void Main(string[] args)
            {
                using (Pipeline pipeline = Pipeline.Create())
                {
                    var store = Store.Create(pipeline, "demo", "C:\\recordings");
                    WaveFormat waveFormat = WaveFormat.Create16kHz1Channel16BitPcm();

                    IProducer <AudioBuffer> audioInput = new AudioCapture(pipeline, new AudioCaptureConfiguration() { OutputFormat = waveFormat });
                    audioInput.Write("audio", store);
                    GoogleSpeechASR gsr = new GoogleSpeechASR(pipeline, "en"); 
                    audioInput.PipeTo(gsr);
                    GoogleTranslate gt = new GoogleTranslate(pipeline, "de");
                    gsr.PipeTo(gt);
                    GoogleSpeak gs = new GoogleSpeak(pipeline, waveFormat, "de-DE");
                    gt.PipeTo(gs);
                    AudioOutput aOut = new AudioOutput(pipeline);
                    gs.PipeTo(aOut);

                    ConsoleOutput c = new ConsoleOutput(pipeline);

                    gsr.PipeTo(c);
                    gt.PipeTo(c);


                    Console.OutputEncoding = Encoding.Unicode;
                    pipeline.RunAsync();


                    Console.ReadKey(true);
                }
            }
        }
    }
}`
