### ISSUE TITLE
Add .NET Core to build instructions

### ISSUE THREAD

**Issue by jokravit** [microsoft/psi#22]
In the build instructions, you specify adding ".NET desktop development workload, as well as the .NET Framework 4.7 targeting pack" however, there is no mention of adding .NET Core (available [here](https://dotnet.microsoft.com/download/dotnet-core/2.0)) which was required for me to successfully build. I believe checking that the ".NET Core cross-platform development" option in the installer would also be sufficient, but I did not test that.

**Comment by danbohus** [comment]
We have added the necessary documentation to the build instructions.
