### ISSUE TITLE
`NullReferenceException` in MixedReality.cs

### ISSUE THREAD

**Issue by austinbhale** [microsoft/psi#270]
I started the app with the HoloLens 2 off my head and received a null exception for `this.stereoKitSpatialCoordinateSystem` here: https://github.com/microsoft/psi/blob/39615ade7dca194770cc645c5c46a2da97000ceb/Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/MixedReality.cs#L179

I believe `SpatialAnchor.TryCreateRelativeTo` will return null when it fails to localize in the environment: https://github.com/microsoft/psi/blob/39615ade7dca194770cc645c5c46a2da97000ceb/Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/Operators.cs#L47

It might be helpful to have a null check somewhere for the failed conversion to a spatial coordinate system, or to keep trying: https://github.com/microsoft/psi/blob/39615ade7dca194770cc645c5c46a2da97000ceb/Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/MixedReality.cs#L144

**Comment by sandrist** [comment]
Good catch! We will add a fix to handle this situation.
