### ISSUE TITLE
Mpeg4Writer incorrect metadata in output .mp4

### ISSUE THREAD

**Issue by chiragraman** [Microsoft/psi#3]
Hello!

I'm using the Mpeg4Writer to write videos captured from a webcam. Playing back the written video in multiple media players indicates that the duration information in the encoded file is incorrect and seeking capability is missing. 

**System and recording details**
OS : Windows 10 v 1709 Build 16299.431
Camera : Tested on both Logitech Brio and Logitech C920 (recording at 1920x1080, 30fps)
Psi packages version : v0.3.16.5-beta through nuget

**Steps to reproduce**
1. Start with the code in the WebcamWithAudioSample
2. Add the following after line 70 in Program.cs that creates the webcam:

```
var writerConfiguration = Mpeg4WriterConfiguration.Default;
writerConfiguration.ContainsAudio = false;
Mpeg4Writer vidWriter = new Mpeg4Writer(pipeline, Path.Combine(pathToStore, "video.mp4"), writerConfiguration);
webcam.Out.PipeTo(vidWriter.ImageIn, DeliveryPolicy.Unlimited);
```

**Playback results**
I've tried playing back the resulting .mp4 (real duration 5sec) in Movies&TV, Windows Media Player, and VLC. Here are the screenshots of each:

Movies&TV:
![movies tv](https://user-images.githubusercontent.com/1950941/40245689-586e20d6-5a94-11e8-8f78-5a3b3154f130.PNG)

Windows Media Player:
![wmp](https://user-images.githubusercontent.com/1950941/40245703-605f079c-5a94-11e8-8b6b-cb259a2221ff.PNG)

VLC:
![vlc](https://user-images.githubusercontent.com/1950941/40245712-66349e52-5a94-11e8-9955-acf49226f476.PNG)

**Comment by pat-sweeney** [comment]
This has been resolved with commit #663bd0528f7c98e9aa545a12d6fb5bb0be987409
