### ISSUE TITLE
PsiStudio not displaying correctly properties with new visualizers

### ISSUE THREAD

**Issue by AuMilliat** [microsoft/psi#301]
Hello,

I'm working on new visualizers for PsiStudio, I have issue getting the property panel working as intended.
As an example, I've made a slight modification on the Azure Kinect Visualizer to display confidence as joint color (nothing changes in the properties).
 
![augmented](https://github.com/microsoft/psi/assets/73344115/829450ec-6d16-4c99-a168-35ad53fa79de)

Expected

![azure](https://github.com/microsoft/psi/assets/73344115/48b57625-f328-4c17-aaab-d6cf193ddd89)

From what I understand objects are not seen as expendable.

3D panel  

![3DView](https://github.com/microsoft/psi/assets/73344115/ed033dba-c5aa-471d-99e1-2c6f4ae72ca8)

 I probably I'm doing wrong something and it will be fixed with #54

**Comment by sandrist** [comment]
Can you share some of the new code?
Does `Skeleton` still have the `[ExpandableObject]` tag above it?

```csharp
/// <summary>
/// Gets the skeleton visualization object for the body.
/// </summary>
[ExpandableObject]
[DataMember]
[PropertyOrder(3)]
[DisplayName("Skeleton")]
[Description("The body's skeleton properties.")]
public SkeletonVisualizationObject<JointId> Skeleton { get; private set; }
```

**Comment by AuMilliat** [comment]
Thanks for the reply,

Here the winmerge of the files (left: modified, right: base)
![winmerge](https://github.com/microsoft/psi/assets/73344115/04dd4e80-2ce5-45b8-b7ff-58f95620cab0)

I've tried to copy-past the kinect visualization project outside \psi repo and I was able to reproduce the issue:

![extract](https://github.com/microsoft/psi/assets/73344115/e3a395cc-611d-442b-939b-2f4c2c43e744)

Integrating my classes inside the \psi repo correct the behavior:

![intern](https://github.com/microsoft/psi/assets/73344115/498b60f8-77fb-4537-837d-1b07001c4698)

So my guess it's related to dependencies.

**Comment by AuMilliat** [comment]
I've corrected the issue by doing the link properly with \psi. I've build from the source those two nugets:
![nuget](https://github.com/microsoft/psi/assets/73344115/da37d254-b2da-45b9-8ad5-aa357cef6e19)

It might worth to publish them on nuget.org!

**Comment by sandrist** [comment]
Thanks for the update! Glad that you are unblocked.
In the future we might put more visualizers in nugets and release PsiStudio as an installable executable. For now, we only support PsiStudio and related visualizers to be built from source.
