### ISSUE TITLE
Documentation update: Brief Introduction Offline Visualisation

### ISSUE THREAD

**Issue by DeCatNiels** [microsoft/psi#45]
This is just a small documentation update that should probably be added.
To be able to run the **brief introduction example: 5.1 Offline Visualization.**
this one --> https://github.com/microsoft/psi/wiki/Brief-Introduction#51-offline-visualization
These Nuget references where missing for me when I was following this introduction:

- Microsoft.Psi.Audio
- Microsoft.Psi.Audio.Windows
- Microsoft.Psi.Imaging
- Microsoft.Psi.Speech

_edit:_
I just found out that this depends on what kind of project is chosen when creating a project.
In the documentation it states that you can take a .netcore console or a .netframework console project. I went for the .netcore one.
But apparently at least in my case these dependent Nuget references weren't added when adding the ones that are in the documentation.

And also because I went for the .netcore project I had to replace `<TargetFramework>netcoreapp3.0</TargetFramework>` with `<TargetFramework>net472</TargetFramework>` in the ".cspjoj" file (project file).

_edit 2:_
I also did some testing right now to see if everything works when you use a .netframework console project.
I found out that indeed the dependent Nuget references are added automaticly when I added the the references specified in the documentation.
But I still had to change something else to be able to run the code. I had to go to my project properties and under build I had to change the "Platform Target" to check "Optimize code" only. (and uncheck "Prefer 32-bit")

**Comment by chitsaw** [comment]
Thank you for reporting this. You're right - Section 5.1 of the tutorial should begin with a new .NET Framework project (with 'Prefer 32-bit' unchecked). We'll update this.

**Comment by chitsaw** [comment]
Updated [the documentation](https://github.com/microsoft/psi/wiki/Brief-Introduction#51-offline-visualization).
