### ISSUE TITLE
Unable to run PsiStudio

### ISSUE THREAD

**Issue by dparkar** [Microsoft/psi#5]
I am following the Offline Visualization [tutorial](https://microsoft.github.io/psi/tutorials/) and trying to run PsiStudio.

When I build and run the PsiStudio project, I get the following error : 

![image](https://user-images.githubusercontent.com/208161/41699277-f5c4335e-74d7-11e8-81db-d355fe2cfc84.png)

Details : 

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Psi.PsiStudio.PsiStudioContext' threw an exception.
  Source=Microsoft.Psi.PsiStudio
  StackTrace:
   at Microsoft.Psi.PsiStudio.PsiStudioContext.get_Instance() in C:\src\Microsoft\psi\Sources\Tools\PsiStudio\Microsoft.Psi.PsiStudio\PsiStudioContext.cs:line 71
   at Microsoft.Psi.PsiStudio.MainWindow..ctor() in C:\src\Microsoft\psi\Sources\Tools\PsiStudio\Microsoft.Psi.PsiStudio\MainWindow.xaml.cs:line 24

Inner Exception 1:
BadImageFormatException: Could not load file or assembly 'Microsoft.Kinect, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

Inner Exception 2:
BadImageFormatException: Cannot load a reference assembly for execution.

I have installed the required and optional pre-requisites mentioned [here](https://microsoft.github.io/psi/BuildingPsi).

Looks like Kinect libraries are required to run PsiStudio. If so, what version ?

**Comment by jdelliot** [comment]
PsiStudio does require the Kinect SDK, found here: https://www.microsoft.com/en-us/download/details.aspx?id=44561.

**Comment by dparkar** [comment]
That worked ! Thanks !
