### ISSUE TITLE
Psi samples take a long time to load!

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/psi#65]
I was hoping I could get the WebcamWithAudioSample.csproj running in a few minutes.  It opened the full Psi solution which took a super long time to open on my laptop.  It would be nice to separate the samples out from the Psi solution so people on not-super-beefy systems can get started with them quickly.  Thanks!

**Comment by danbohus** [comment]
Agreed, thanks for the feedback! We are investigating migrating the samples to their own solution and to directly using nuget packages.

**Comment by chitsaw** [comment]
Samples are now in a separate repo and build against nugets: https://github.com/microsoft/psi-samples
