### ISSUE TITLE
Steps to run WebCamWithAudioSample should be included in sample README.

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/psi#66]
I'm getting these errors when I build the Psi solution, and I don't know offhand which components are necessary for the sample.  The sample's README file would be a great place to put this information.  Thanks!

![image](https://user-images.githubusercontent.com/21269347/87624408-90a41a80-c6dc-11ea-9246-7e05654c5365.png)

**Comment by chitsaw** [comment]
Samples have been updated and moved to: https://github.com/microsoft/psi-samples
