### ISSUE TITLE
Spectre-mitigated components installed, but still getting errors

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/psi#67]
Following the instructions in [Building the Codebase](https://github.com/microsoft/psi/wiki/Building-the-Codebase), I installed the Spectre-mitigated packages:

![image](https://user-images.githubusercontent.com/21269347/87626628-acf68600-c6e1-11ea-8560-4eff51dbb5b7.png)

I'm still getting these errors:

![image](https://user-images.githubusercontent.com/21269347/87626653-bb44a200-c6e1-11ea-9c00-d6ec45125561.png)

Help?

**Comment by chitsaw** [comment]
I think you may need to install v14.26 of the Spectre-mitigated libs instead since that is now the latest version. Could you try installing that and let us know if it works? If so we should also update the instructions :-)

**Comment by annelo-msft** [comment]
Yes, that worked - it builds now!

![image](https://user-images.githubusercontent.com/21269347/87690360-376cd300-c73e-11ea-9d62-d4ce6921346f.png)

Thank you so much!! :)
