### ISSUE TITLE
Live Visualization : System.BadImageFormatException

### ISSUE THREAD

**Issue by dparkar** [Microsoft/psi#7]
I am following the steps mentioned [here](https://microsoft.github.io/psi/tutorials#LiveVisualization) to try out live visualization. Running the application produces the following unhandled exception : 

System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'Microsoft.Psi.Visualization.Client.Windows, Version=0.3.16.5, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

![image](https://user-images.githubusercontent.com/208161/42013033-2485e192-7a50-11e8-84b1-3a770ba64e16.png)

Note that I have run PsiStudio once before this. I am using Microsoft.Psi.Visualization.Windows 0.3.16.5-beta from nuget and targeting .NET 4.7.

**Comment by jdelliot** [comment]
System.BadImageFormatExcetpion is often thrown when there is a mismatch between x86 and x64 assemblies. I thought the code supported invoking the remote visualization commands from x86 code, I suspect this may not be the case. Would you try changing your project to explicitly choose x64 as the "Platform target"?

You can do this by going to your project properties, selecting the Build tab and choosing x64 from Platform target dropdown options.

In the meantime I will try to repro by creating a simple test client and see what results I get.

**Comment by dparkar** [comment]
Changing to x64 seems to launch PsiStudio, but produces another exception : 

![image](https://user-images.githubusercontent.com/208161/42069471-e211a2ee-7b06-11e8-9406-fd0e3abbd452.png)

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
  Source=Microsoft.Psi.Visualization.Client.Windows
  StackTrace:
   at Microsoft.Psi.Visualization.Client.VisualizationClient.EnsureBinding(StreamBinding streamBinding)
   at Microsoft.Psi.Visualization.Client.VisualizationClient.Show[TObject,TData,TConfig,TPanel](StreamBinding streamBinding)
   at Microsoft.Psi.Visualization.Client.VisualizationClientExtensions.Show(IProducer`1 stream, VisualizationClient vc)
   at PsiLiveVis.Program.Main(String[] args) in C:\src\local\PsiLiveVis\PsiLiveVis\Program.cs:line 33

**Comment by jdelliot** [comment]
It seems like the NuGet package for the visualization client (Microsoft.Psi.Visualization.Client.Windows) should have propagated a dependency for Newtonsoft.Json, but it didn't. Did you add it manually and things worked?

**Comment by dparkar** [comment]
That's correct. The PR and the previous comments has the updates.
