### ISSUE TITLE
[Bug] should `StreamMetadataBase.cs`  be in `Microsoft.Psi` namespace?

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/psi#80]
Maybe I misunderstood how[ `StreamMetadataBase.cs` ](https://github.com/microsoft/psi/blob/master/Sources/Runtime/Microsoft.Psi/Common/StreamMetadataBase.cs) works, but shouldn't it be in the `Microsoft.Psi` namespace instead of `Microsoft.Psi.Audio`?

**Comment by chitsaw** [comment]
You're absolutely right. Thanks for the find!
