### ISSUE TITLE
[Who's Using] TBD Lab + Components!

### ISSUE THREAD

**Issue by xiangzhi** [microsoft/psi#96]
Here's the link to our lab's publicly released Psi Components (https://github.com/CMU-TBD/TBD.Psi.Components). I guess the most exciting among them is the ROSBag Stream Reader that was built upon the old converter. It will be great if you can add this to the wiki.

You can also add us to the `who's using` section with the markdown code `the [Transportation, Bots, & Disability Lab](tbd.ri.cmu.edu) at the Carnegie Mellon University`. 

Thanks!

**Comment by danbohus** [comment]
Great, thanks a lot! We have updated the corresponding pages.
